<a href="https://colab.research.google.com/github/Saitou0813/DeepLearning2022Late/blob/main/NumPyReplay2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPyを使用する

In [1]:
# numpyというライブラリをインポートする as npでnpという名前で動かせるようにする
import numpy as  np

### 配列(アレイ)を作る

In [2]:
# xという変数に[1,2,3,4,5]という配列を入れて出力
# arrayはリストを渡すことでnumpy用の配列を生成してくれる
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)

[1. 2. 3. 4. 5.]


In [3]:
# type(x)でxのクラスを出力
x = np.array([1,2,3])
print(x) # [1 2 3]
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
my_list1 = [1,2,3,4,5]
my_array1 = np.array(my_list1)

In [5]:
my_list2 = [10,20,30,40,50]
# リストのリストを作って出力
my_lists = [my_list1, my_list2]
my_lists

[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]

In [6]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [7]:
# エラー例 コードで実行するとTypeErrorがでる
# np.array((1,2,3),(4,5,6))

TypeError: ignored

### NumPy配列の形状を調べる

In [9]:
a = np.array([1, 2, 3, 4])
a.shape

(4,)

In [10]:
b = np.array([[1, 2],[3,4]])
b.shape

(2, 2)

### 配列の生成 arange()

In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
x = np.arange(1, 10).reshape(3,3)
y = np.arange(1, 10).reshape(3,3)
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(x + y)
print(x - y)
print(x * y)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 配列操作

In [15]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(np.concatenate([sample_array3,sample_array4],axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
print(np.hstack((sample_array3,sample_array4)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [20]:
print(np.concatenate([sample_array3,sample_array4],axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
print(np.vstack((sample_array3,sample_array4)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### ブロードキャスト

In [22]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(sample_array + 5)

[ 5  6  7  8  9 10 11 12 13 14]


### 多次元配列の計算

In [24]:
n1 = np.array([1,2,3,4,5])
print(n1)

[1 2 3 4 5]


In [25]:
np.ndim(n1)

1

In [26]:
n1.shape

(5,)

In [27]:
n2 = np.array([[1,2], [3,4], [5,6]])
print(n2)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
print(n2.ndim)

2


### 行列とは

In [29]:
my_li1 = [-1,4]
my_li2 = [3,2]
my_li3 = [2,5]
my_li4 = [0,1]
my_lists = [my_li1,my_li2,my_li3,my_li4]

my_array3 = np.array(my_lists)

my_array3

array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])